ebs: /ebs
capacities: # in GB
  memory-cap: 60 
  ebs-cap: 256
threads:
  memory: 4
  ebs: 4
  routing: 4
  benchmark: 6
replication:
  memory: 4
  ebs: 0
  minimum: 1
  local: 4
policy:
  elasticity: false
  selective-rep: false
  tiering: false
